Version bump for spotlss and apache commons
Spotless fails in 2.x branch with old version with following error
`Caused by: java.lang.NoSuchMethodError: 'long com.sun.tools.javac.tree.DCTree$DCReference.getSourcePosition(com.sun.tools.javac.tree.DCTree$DCDocComment)'`

Signed-off-by: Heemin Kim <heemin@amazon.com>