Version bump for spotlss and apache commons (#400) (#402)
Spotless fails in 2.x branch with old version with following error
`Caused by: java.lang.NoSuchMethodError: 'long com.sun.tools.javac.tree.DCTree$DCReference.getSourcePosition(com.sun.tools.javac.tree.DCTree$DCDocComment)'`

Signed-off-by: Heemin Kim <heemin@amazon.com>
(cherry picked from commit cd3e21117880be6ce2c3e6be47c2023f33b29dd0)

Co-authored-by: Heemin Kim <heemin@amazon.com>